"""empty message

Revision ID: fa95d56617ea
Revises: eb9af20abc6e
Create Date: 2025-03-19 00:11:27.831357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa95d56617ea'
down_revision: Union[str, None] = 'eb9af20abc6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(length=1024),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.String(length=1024),
               type_=postgresql.BYTEA(),
               existing_nullable=False)
    # ### end Alembic commands ###
